apiVersion: apps/v1
kind: Deployment
metadata: 
  name: react-sandbox-deployment
spec: 
  selector: 
    matchLabels:
      app: react-sandbox
  replicas: 1
  template:
    metadata:
      labels: 
        app: react-sandbox
    spec:
      containers:
      - name: react-sandbox
        image: ${DOCKER_IMAGE_REGISTRY}:${DOCKER_IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: react-sandbox
spec:
  selector:
    app: react-sandbox
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  type: LoadBalancer