apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: cloudbankdb
spec:
  details:
    compartmentOCID: %ADB_OCID%
    lifecycleState: TERMINATED
  ociConfig:
    configMapName: oci-cred
    secretName: oci-privatekey