apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: cloudbankdb
spec:
  details:
    compartmentOCID: %ADB_COMPARTMENT%
    dbName: cloudbankdb
    displayName: cloudbankdb
    cpuCoreCount: 1
    adminPassword:
      k8sSecret:
        name: admin-password

    dataStorageSizeInTBs: 1
  hardLink: true
  ociConfig:
    configMapName: oci-cred
    secretName: oci-privatekey