apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: cloudbankdb
  namespace: cloudbank-app
spec:
  details:
    autonomousDatabaseOCID: %ADB_OCID%
    networkAccess:
      accessType: RESTRICTED
      accessControlList:
      - 0.0.0.0/0
  ociConfig:
    configMapName: oci-cred
    secretName: oci-privatekey

---
apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: cloudbankdb
  namespace: cloudbank-app  
spec:
  details:
    autonomousDatabaseOCID: %ADB_OCID%
    networkAccess:
      isMTLSConnectionRequired: false
  ociConfig:
    configMapName: oci-cred
    secretName: oci-privatekey