apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: cloudbankdb
  namespace: cloudbank-db
spec:

  ## DB edition
  edition: express

  ## Secret containing SIDB password mapped to secretKey
  adminPassword:
    secretName: sidb-admin-secret

  ## Database Image
  image:
    pullFrom: container-registry.oracle.com/database/express:latest
    prebuiltDB: true

  ## Persistence is optional for prebuilt DB image
  ## if specified, the prebuilt DB datafiles are copied over to the persistant volume before DB startup
  #persistence:
  #  size: 50Gi
  #  storageClass: "oci-bv"
  #  accessMode: "ReadWriteOnce"

  ## Count of Database Pods.
  replicas: 1