#
# Copyright (c) 2021, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: {{DB_NAME}}
spec:
  details:
    # Update compartmentOCID with your compartment OCID.
    compartmentOCID: {{OCI_COMPARTMENT_OCID}}
    # The dbName must begin with an alphabetic character and can contain a maximum of 14 alphanumeric characters. 
    # Special characters are not permitted. The database name must be unique in the tenancy.
    dbName: {{DB_RESOURCE_NAME}}
    displayName: {{DB_DISPLAY_NAME}}
    cpuCoreCount: 1
    adminPassword:
      k8sSecretName: {{DB_PSWD_SEC}}
    dataStorageSizeInTBs: 1
  ociConfig:
    configMapName: {{OCI_CONFIG}}
    secretName: {{OCI_PRIVKEY_SEC}}