apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: cloudbankdb
spec:
  details:
    autonomousDatabaseOCID: %ADB_COMPARTMENT%
  hardLink: true
  ociConfig:
    configMapName: oci-cred
    secretName: oci-privatekey