## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: %CLOUDBANK_APP_IMAGE%
          imagePullPolicy: Always
          env:
            - name: CLOUDBANK_SECURITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: %CLOUDBANK_SECURITY_PWD_SECRET_NAME%
                  key: %CLOUDBANK_SECURITY_PWD_SECRET_KEY%
                  optional: true
            - name: CLOUDBANK_SECURITY_USERNAME
              value: %CLOUDBANK_SECURITY_USERNAME%
            - name: CLOUDBANK_APIS_BANKA
              value: %CLOUDBANK_APIS_BANKA%
            - name: CLOUDBANK_APIS_BANKB
              value: %CLOUDBANK_APIS_BANKB%
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: 10
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: 100
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"


    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: ssl-certificate-secret
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 8080
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: frontend


